### ISSUE TITLE
Create two labels in the same row

### ISSUE THREAD

**Issue by NVAT** [igroomgrim/howtoplaysnapkit#1]
I am trying to create labels constraint in the same row with offset each other and superview,for example offset with superview equal 20pt but offset each other no fixed.

**Comment by igroomgrim** [comment]
Can you try like this, use ViewAttribute for reference 

label1.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(20)
        }

label2.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(label1.snp_right).offset(20)
        }
`

Thanks :dancers:

**Comment by NVAT** [comment]
@igroomgrim I want the first label to "compact" but the second label to never compact?

**Comment by igroomgrim** [comment]
Can you show layout that you need in image type?

**Comment by NVAT** [comment]
![simulator screen shot feb 9 2016 10 36 23](https://cloud.githubusercontent.com/assets/16933227/12912573/7ce62d20-cf2a-11e5-8b5d-21e8fb968700.png)

**Comment by NVAT** [comment]
This is my code

``` Swift
     let docNumber = UILabel()
        docNumber.text = "234234"
        docNumber.lineBreakMode = .ByTruncatingMiddle
        self.view.addSubview(docNumber)


        let docTitle = UILabel()
        docTitle.text = "Document number of loan contract"
        docTitle.lineBreakMode = .ByTruncatingMiddle
        self.view.addSubview(docTitle)


        docTitle.snp_makeConstraints { make in
            make.left.top.equalTo(view).offset(20)            
        }

           docNumber.snp_makeConstraints { make in
            make.top.equalTo(docTitle.snp_top)
            make.left.equalTo(docTitle.snp_right).offset(-8)
            make.right.equalTo(view).offset(-20)

        }
```

**Comment by igroomgrim** [comment]
You can try to add 

```
docTitle.adjustsFontSizeToFitWidth = true
```

and 

```
docNumber.snp_makeConstraints { make in
            make.top.equalTo(docTitle.snp_top)
            make.left.equalTo(docTitle.snp_right).offset(8)
            make.right.equalTo(view).offset(-20)

        }
```

**Comment by NVAT** [comment]
Thanks,but I would not to change font size,I need to truncate left label text,create compact and right label to be static

**Comment by igroomgrim** [comment]
It's nice. Enjoy your code :v:
